name: ci-release-notes
on:
  release:
    types:
    - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: release notes
      run: |
        TAG=${GITHUB_REF/refs\/tags\/}
        npx github-release-notes release --override --tags ${TAG}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GREN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
