liquibase:
  enabled: false
spring:
  application:
    name: verification-server
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:ELMO;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
tan:
  tele:
    valid:
      days: 14
      hours: 1
  valid:
    days: 14
uri:
  endpoint:
    labserver: http://labtestresults-test.telekom-healthcare.com:30000
    
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
