liquibase:
  enabled: false
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:ELMO;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
tan:
  tele:
    valid:
      hours: 1
  valid:
    days: 14
appsession:
    tancountermax: 2
uri:
  endpoint:
    labserver: http://labtestresults-test.telekom-healthcare.com:30000
