logging:
  level:
    org:
      springframework:
        web: INFO
liquibase:
  enabled: false
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:ELMO;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
tan:
  tele:
    valid:
      days: 7
  valid:
    days: 7
uri:
  endpoint:
    labserver: http://localhost:8088
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
